server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址，写死了
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言， 路径相匹配的进行路由
            - After=2021-05-29T21:05:44.551+08:00[Asia/Shanghai]

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            - After=2021-05-29T21:05:44.551+08:00[Asia/Shanghai]
            - Cookie=username,zzyy
            - Header=X-Request-Id,\d+  #请求头要有X-Request-Id属性，并且值为整数的正则表达式
            - Method=GET
#            - Query=username, \d+ #要有参数名username并且值还是整数才能路由
eureka:
  client:
    #表示向注册中心注册自己， 默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息， 默认为true, 单节点无所谓， 集群必须设置为True才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
