server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称， 用于与Binding整合
          type: rabbit  #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        output: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange名称定义
          content_type: application/json # 设置消息类型， 本次为json, 文本则设置为 "text/json"
          binder: defaultRabbit #设置要绑定的消息服务的具体位置


#服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #Eureka客户端向服务端发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 5 #Eureka服务端在收到最后一次心跳后等待上限时间，超时剔除服务
    instance-id: send-8801.com
    prefer-ip-address: true


