server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false # 只作为客户端，不注册机进eureka了
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版
      #defaultZone: http://localhost:7001/eureka #单机版
#设置Feign客户端超时时间（openfign默认支持ribbon）
ribbon:
  #指的是建立连接所用时间，适用于网络正常情况下，两端连接所用时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 5000

#Feign日志增强
logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.scj.springcloud.service.PaymentFeignService: debug