server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string:   120.26.170.124:2181  #zookeeper 的 ip : port
      discovery:
        enabled: true
