server:
  port: 8402
spring:
  application:
    name: cloudalibaba-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务注册中心地址
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口， 假如被占用会自动从8719开始 + 1 扫描，直到找到未用得端口
        port: 8719

service-url:
  nacos-user-service: http://cloudalibaba-sentinel-server

management:
  endpoints:
    web:
      exposure:
        include: '*'
